FROM opensearchproject/opensearch:1.3.13
RUN bin/opensearch-plugin install https://storage.yandexcloud.net/adc-libraries/opensearch-analysis-morphology-1.3.13.zip
LABEL version="1.3.13morphology" 
CMD ["bin/opensearch"]

